version: "3.8"

services:
  angular-app:
    build: .
    container_name: angular-app
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    env_file:
      - .env
